import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function GET() {
  const posts = await prisma.blogPost.findMany({
    select: {
      id: true,
      slug: true,
      title: true,
      excerpt: true,
      category: true,
      readTime: true,
      publishedAt: true,
      autoGenerated: true,
    },
    orderBy: { publishedAt: "desc" },
  });

  return NextResponse.json({ posts });
}

export async function POST(req: Request) {
  const secret = req.headers.get("x-blog-secret");
  if (!secret || secret !== process.env.BLOG_GENERATE_SECRET) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await req.json();
  const { slug, title, excerpt, content, category, readTime, autoGenerated } = body;

  if (!slug || !title || !content) {
    return NextResponse.json({ error: "slug, title and content are required" }, { status: 400 });
  }

  const post = await prisma.blogPost.upsert({
    where: { slug },
    update: { title, excerpt, content, category, readTime, autoGenerated: autoGenerated ?? true, publishedAt: new Date() },
    create: { slug, title, excerpt: excerpt ?? "", content, category: category ?? "Analysis", readTime: readTime ?? "5 min read", autoGenerated: autoGenerated ?? true },
  });

  return NextResponse.json({ post }, { status: 201 });
}
